// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Normative.Data;

#nullable disable

namespace Normative.Migrations
{
    [DbContext(typeof(NormativeContext))]
    partial class NormativeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Normative.Models.Config.Permissions", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions", "cfg");
                });

            modelBuilder.Entity("Normative.Models.Config.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles", "cfg");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Created = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vladce vseho",
                            IsActive = true,
                            Name = "Administrator"
                        },
                        new
                        {
                            RoleId = 2,
                            Created = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Peasant",
                            IsActive = true,
                            Name = "Technologie"
                        });
                });

            modelBuilder.Entity("Normative.Models.Config.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions", "cfg");
                });

            modelBuilder.Entity("Normative.Models.Config.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.ToTable("Users", "cfg");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Created = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Petr Docekal",
                            Email = "peta.docekal@gmail.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$hHUW/3Rj/1lYTjQOC3K2B.2Nvt7yQgaSTOBJ358FkrOpb2CXPPM8.",
                            UserName = "peta_3"
                        });
                });

            modelBuilder.Entity("Normative.Models.Config.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles", "cfg");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Normative.Models.PreparationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("PreparationType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Příprava materiálu"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Příprava svarových ploch"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Příprava povrchu"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Příprava přírub"
                        });
                });

            modelBuilder.Entity("Normative.Models.STD.Pipe.V_VTC_Pipe_20_30", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("D1800VT3_20")
                        .HasColumnType("int")
                        .HasColumnName("D1800_VT3_20");

                    b.Property<int?>("D1800VT3_30")
                        .HasColumnType("int")
                        .HasColumnName("D1800_VT3_30");

                    b.Property<int?>("D1800VT6_20")
                        .HasColumnType("int")
                        .HasColumnName("D1800_VT6_20");

                    b.Property<int?>("D1800VT6_30")
                        .HasColumnType("int")
                        .HasColumnName("D1800_VT6_30");

                    b.Property<int?>("D1800VT9_20")
                        .HasColumnType("int")
                        .HasColumnName("D1800_VT9_20");

                    b.Property<int?>("D1800VT9_30")
                        .HasColumnType("int")
                        .HasColumnName("D1800_VT9_30");

                    b.Property<int?>("D2100VT11_20")
                        .HasColumnType("int")
                        .HasColumnName("D2100_VT11_20");

                    b.Property<int?>("D2100VT11_30")
                        .HasColumnType("int")
                        .HasColumnName("D2100_VT11_30");

                    b.Property<int?>("D2100VT16_20")
                        .HasColumnType("int")
                        .HasColumnName("D2100_VT16_20");

                    b.Property<int?>("D2100VT16_30")
                        .HasColumnType("int")
                        .HasColumnName("D2100_VT16_30");

                    b.Property<int?>("D2100VT21_20")
                        .HasColumnType("int")
                        .HasColumnName("D2100_VT21_20");

                    b.Property<int?>("D2100VT21_30")
                        .HasColumnType("int")
                        .HasColumnName("D2100_VT21_30");

                    b.Property<int?>("D2100VT25_20")
                        .HasColumnType("int")
                        .HasColumnName("D2100_VT25_20");

                    b.Property<int?>("D2100VT25_30")
                        .HasColumnType("int")
                        .HasColumnName("D2100_VT25_30");

                    b.Property<int?>("D2500VT26_20")
                        .HasColumnType("int")
                        .HasColumnName("D2500_VT26_20");

                    b.Property<int?>("D2500VT26_30")
                        .HasColumnType("int")
                        .HasColumnName("D2500_VT26_30");

                    b.Property<int?>("D2500VT31_20")
                        .HasColumnType("int")
                        .HasColumnName("D2500_VT31_20");

                    b.Property<int?>("D2500VT31_30")
                        .HasColumnType("int")
                        .HasColumnName("D2500_VT31_30");

                    b.Property<int?>("D2500VT43_20")
                        .HasColumnType("int")
                        .HasColumnName("D2500_VT43_20");

                    b.Property<int?>("D2500VT43_30")
                        .HasColumnType("int")
                        .HasColumnName("D2500_VT43_30");

                    b.Property<int?>("D3000VT41_20")
                        .HasColumnType("int")
                        .HasColumnName("D3000_VT41_20");

                    b.Property<int?>("D3000VT41_30")
                        .HasColumnType("int")
                        .HasColumnName("D3000_VT41_30");

                    b.Property<int?>("D3000VT50_20")
                        .HasColumnType("int")
                        .HasColumnName("D3000_VT50_20");

                    b.Property<int?>("D3000VT50_30")
                        .HasColumnType("int")
                        .HasColumnName("D3000_VT50_30");

                    b.Property<int?>("D3000VT60_20")
                        .HasColumnType("int")
                        .HasColumnName("D3000_VT60_20");

                    b.Property<int?>("D3000VT60_30")
                        .HasColumnType("int")
                        .HasColumnName("D3000_VT60_30");

                    b.Property<string>("Diameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrawingPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOperationStep")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Note_20")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Note_20");

                    b.Property<string>("Note_30")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Note_30");

                    b.Property<int?>("OperationId_20")
                        .HasColumnType("int")
                        .HasColumnName("OperationId_20");

                    b.Property<int?>("OperationId_30")
                        .HasColumnType("int")
                        .HasColumnName("OperationId_30");

                    b.Property<int?>("PipeBending")
                        .HasColumnType("int");

                    b.Property<string>("ProductLine")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.Property<int?>("ProductSizeId")
                        .HasColumnType("int");

                    b.Property<string>("ProductType")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("v_VTC_Pipe_20_30", (string)null);
                });

            modelBuilder.Entity("Normative.Models.STD.Pipe.V_VTC_Pipe_OPSQ_20", b =>
                {
                    b.Property<int?>("D1800VT3")
                        .HasColumnType("int")
                        .HasColumnName("D1800_VT3");

                    b.Property<int?>("D1800VT6")
                        .HasColumnType("int")
                        .HasColumnName("D1800_VT6");

                    b.Property<int?>("D1800VT9")
                        .HasColumnType("int")
                        .HasColumnName("D1800_VT9");

                    b.Property<int?>("D2100VT11")
                        .HasColumnType("int")
                        .HasColumnName("D2100_VT11");

                    b.Property<int?>("D2100VT16")
                        .HasColumnType("int")
                        .HasColumnName("D2100_VT16");

                    b.Property<int?>("D2100VT21")
                        .HasColumnType("int")
                        .HasColumnName("D2100_VT21");

                    b.Property<int?>("D2100VT25")
                        .HasColumnType("int")
                        .HasColumnName("D2100_VT25");

                    b.Property<int?>("D2500VT26")
                        .HasColumnType("int")
                        .HasColumnName("D2500_VT26");

                    b.Property<int?>("D2500VT31")
                        .HasColumnType("int")
                        .HasColumnName("D2500_VT31");

                    b.Property<int?>("D2500VT43")
                        .HasColumnType("int")
                        .HasColumnName("D2500_VT43");

                    b.Property<int?>("D3000VT41")
                        .HasColumnType("int")
                        .HasColumnName("D3000_VT41");

                    b.Property<int?>("D3000VT50")
                        .HasColumnType("int")
                        .HasColumnName("D3000_VT50");

                    b.Property<int?>("D3000VT60")
                        .HasColumnType("int")
                        .HasColumnName("D3000_VT60");

                    b.Property<string>("Diameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrawingPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("NameOperationStep")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("OperationId")
                        .HasColumnType("int")
                        .HasColumnName("Operation_Id");

                    b.Property<int?>("PipeBending")
                        .HasColumnType("int");

                    b.Property<string>("ProductLine")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.Property<int?>("ProductSizeId")
                        .HasColumnType("int")
                        .HasColumnName("ProductSize_Id");

                    b.Property<string>("ProductType")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.ToTable((string)null);

                    b.ToView("v_VTC_Pipe_OPSQ_20", (string)null);
                });

            modelBuilder.Entity("Normative.Models.STD.Pipe.V_VTC_Pipe_OPSQ_30", b =>
                {
                    b.Property<int?>("D1800VT3")
                        .HasColumnType("int")
                        .HasColumnName("D1800_VT3");

                    b.Property<int?>("D1800VT6")
                        .HasColumnType("int")
                        .HasColumnName("D1800_VT6");

                    b.Property<int?>("D1800VT9")
                        .HasColumnType("int")
                        .HasColumnName("D1800_VT9");

                    b.Property<int?>("D2100VT11")
                        .HasColumnType("int")
                        .HasColumnName("D2100_VT11");

                    b.Property<int?>("D2100VT16")
                        .HasColumnType("int")
                        .HasColumnName("D2100_VT16");

                    b.Property<int?>("D2100VT21")
                        .HasColumnType("int")
                        .HasColumnName("D2100_VT21");

                    b.Property<int?>("D2100VT25")
                        .HasColumnType("int")
                        .HasColumnName("D2100_VT25");

                    b.Property<int?>("D2500VT26")
                        .HasColumnType("int")
                        .HasColumnName("D2500_VT26");

                    b.Property<int?>("D2500VT31")
                        .HasColumnType("int")
                        .HasColumnName("D2500_VT31");

                    b.Property<int?>("D2500VT43")
                        .HasColumnType("int")
                        .HasColumnName("D2500_VT43");

                    b.Property<int?>("D3000VT41")
                        .HasColumnType("int")
                        .HasColumnName("D3000_VT41");

                    b.Property<int?>("D3000VT50")
                        .HasColumnType("int")
                        .HasColumnName("D3000_VT50");

                    b.Property<int?>("D3000VT60")
                        .HasColumnType("int")
                        .HasColumnName("D3000_VT60");

                    b.Property<string>("Diameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrawingPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("NameOperationStep")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("OperationId")
                        .HasColumnType("int")
                        .HasColumnName("Operation_Id");

                    b.Property<int?>("PipeBending")
                        .HasColumnType("int");

                    b.Property<string>("ProductLine")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.Property<int?>("ProductSizeId")
                        .HasColumnType("int")
                        .HasColumnName("ProductSize_Id");

                    b.Property<string>("ProductType")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.ToTable((string)null);

                    b.ToView("v_VTC_Pipe_OPSQ_30", (string)null);
                });

            modelBuilder.Entity("Normative.Models.Screen.Settings.ViewUsersRoles", b =>
                {
                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("V_UsersRoles", (string)null);
                });

            modelBuilder.Entity("Normative.Models.Table.Operation", b =>
                {
                    b.Property<int>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Operation_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperationId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OperationDescription")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.Property<int?>("OperationNumber")
                        .HasColumnType("int");

                    b.Property<int?>("ProductLineId")
                        .HasColumnType("int")
                        .HasColumnName("ProductLine_Id");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ProductType_Id");

                    b.Property<string>("WorkCenter")
                        .HasMaxLength(31)
                        .IsUnicode(false)
                        .HasColumnType("varchar(31)");

                    b.HasKey("OperationId")
                        .HasName("PK__Operace__3214EC271F9E5207");

                    b.HasIndex("ProductLineId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Operation");

                    b.HasData(
                        new
                        {
                            OperationId = 1,
                            IsDeleted = false,
                            OperationDescription = "Řezání a tvarování potrubí",
                            OperationNumber = 10,
                            ProductLineId = 1,
                            ProductTypeId = 1,
                            WorkCenter = "WC-10"
                        },
                        new
                        {
                            OperationId = 2,
                            IsDeleted = false,
                            OperationDescription = "Svařování potrubí",
                            OperationNumber = 20,
                            ProductLineId = 1,
                            ProductTypeId = 1,
                            WorkCenter = "WC-20"
                        },
                        new
                        {
                            OperationId = 3,
                            IsDeleted = false,
                            OperationDescription = "Řezání tlakového potrubí",
                            OperationNumber = 10,
                            ProductLineId = 1,
                            ProductTypeId = 2,
                            WorkCenter = "WC-10"
                        },
                        new
                        {
                            OperationId = 4,
                            IsDeleted = false,
                            OperationDescription = "Svařování tlakového potrubí",
                            OperationNumber = 20,
                            ProductLineId = 1,
                            ProductTypeId = 2,
                            WorkCenter = "WC-20"
                        },
                        new
                        {
                            OperationId = 5,
                            IsDeleted = false,
                            OperationDescription = "Tlaková zkouška",
                            OperationNumber = 30,
                            ProductLineId = 1,
                            ProductTypeId = 2,
                            WorkCenter = "WC-30"
                        },
                        new
                        {
                            OperationId = 6,
                            IsDeleted = false,
                            OperationDescription = "Příprava pláště nádoby",
                            OperationNumber = 10,
                            ProductLineId = 2,
                            ProductTypeId = 2,
                            WorkCenter = "WC-10"
                        },
                        new
                        {
                            OperationId = 7,
                            IsDeleted = false,
                            OperationDescription = "Svařování dna a víka",
                            OperationNumber = 20,
                            ProductLineId = 2,
                            ProductTypeId = 2,
                            WorkCenter = "WC-20"
                        },
                        new
                        {
                            OperationId = 8,
                            IsDeleted = false,
                            OperationDescription = "Kontrola a certifikace",
                            OperationNumber = 40,
                            ProductLineId = 2,
                            ProductTypeId = 2,
                            WorkCenter = "WC-40"
                        },
                        new
                        {
                            OperationId = 9,
                            IsDeleted = false,
                            OperationDescription = "Příprava nerezového pláště",
                            OperationNumber = 10,
                            ProductLineId = 2,
                            ProductTypeId = 3,
                            WorkCenter = "WC-10"
                        },
                        new
                        {
                            OperationId = 10,
                            IsDeleted = false,
                            OperationDescription = "TIG svařování nerezových dílů",
                            OperationNumber = 20,
                            ProductLineId = 2,
                            ProductTypeId = 3,
                            WorkCenter = "WC-20"
                        },
                        new
                        {
                            OperationId = 11,
                            IsDeleted = false,
                            OperationDescription = "Příprava trubkových svazků",
                            OperationNumber = 10,
                            ProductLineId = 3,
                            ProductTypeId = 2,
                            WorkCenter = "WC-10"
                        },
                        new
                        {
                            OperationId = 12,
                            IsDeleted = false,
                            OperationDescription = "Montáž trubkového svazku do pláště",
                            OperationNumber = 20,
                            ProductLineId = 3,
                            ProductTypeId = 2,
                            WorkCenter = "WC-20"
                        });
                });

            modelBuilder.Entity("Normative.Models.Table.OperationStep", b =>
                {
                    b.Property<int>("OperationStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OperationStep_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperationStepId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Diameter")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DrawingPosition")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("OperationId")
                        .HasColumnType("int")
                        .HasColumnName("Operation_Id");

                    b.Property<int?>("PipeBending")
                        .HasColumnType("int");

                    b.Property<int?>("ProductSizeId")
                        .HasColumnType("int")
                        .HasColumnName("ProductSize_Id");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<int?>("StandardHour")
                        .HasColumnType("int");

                    b.HasKey("OperationStepId");

                    b.HasIndex("OperationId");

                    b.HasIndex("ProductSizeId");

                    b.ToTable("OperationStep");

                    b.HasData(
                        new
                        {
                            OperationStepId = 1,
                            Diameter = "DN50",
                            DrawingPosition = "P-01",
                            IsDeleted = false,
                            Name = "Odměření a označení",
                            OperationId = 1,
                            ProductSizeId = 1,
                            Sequence = 1,
                            StandardHour = 5
                        },
                        new
                        {
                            OperationStepId = 2,
                            Diameter = "DN50",
                            DrawingPosition = "P-02",
                            IsDeleted = false,
                            Name = "Řezání pásovou pilou",
                            OperationId = 1,
                            ProductSizeId = 1,
                            Sequence = 2,
                            StandardHour = 10
                        },
                        new
                        {
                            OperationStepId = 3,
                            Diameter = "DN100",
                            DrawingPosition = "P-01",
                            IsDeleted = false,
                            Name = "Odměření a označení",
                            OperationId = 1,
                            ProductSizeId = 2,
                            Sequence = 1,
                            StandardHour = 7
                        },
                        new
                        {
                            OperationStepId = 4,
                            Diameter = "DN100",
                            DrawingPosition = "P-02",
                            IsDeleted = false,
                            Name = "Řezání pásovou pilou",
                            OperationId = 1,
                            ProductSizeId = 2,
                            Sequence = 2,
                            StandardHour = 15
                        },
                        new
                        {
                            OperationStepId = 5,
                            Diameter = "DN200",
                            DrawingPosition = "P-01",
                            IsDeleted = false,
                            Name = "Odměření a označení",
                            OperationId = 1,
                            ProductSizeId = 3,
                            Sequence = 1,
                            StandardHour = 10
                        },
                        new
                        {
                            OperationStepId = 6,
                            Diameter = "DN200",
                            DrawingPosition = "P-02",
                            IsDeleted = false,
                            Name = "Plasma řezání",
                            OperationId = 1,
                            ProductSizeId = 3,
                            Sequence = 2,
                            StandardHour = 25
                        },
                        new
                        {
                            OperationStepId = 7,
                            Diameter = "DN50",
                            DrawingPosition = "S-01",
                            IsDeleted = false,
                            Name = "Stehování",
                            OperationId = 2,
                            ProductSizeId = 1,
                            Sequence = 1,
                            StandardHour = 15
                        },
                        new
                        {
                            OperationStepId = 8,
                            Diameter = "DN50",
                            DrawingPosition = "S-02",
                            IsDeleted = false,
                            Name = "Svařování MIG",
                            OperationId = 2,
                            ProductSizeId = 1,
                            Sequence = 2,
                            StandardHour = 30
                        },
                        new
                        {
                            OperationStepId = 9,
                            Diameter = "DN100",
                            DrawingPosition = "S-01",
                            IsDeleted = false,
                            Name = "Stehování",
                            OperationId = 2,
                            ProductSizeId = 2,
                            Sequence = 1,
                            StandardHour = 20
                        },
                        new
                        {
                            OperationStepId = 10,
                            Diameter = "DN100",
                            DrawingPosition = "S-02",
                            IsDeleted = false,
                            Name = "Svařování MIG",
                            OperationId = 2,
                            ProductSizeId = 2,
                            Sequence = 2,
                            StandardHour = 50
                        },
                        new
                        {
                            OperationStepId = 11,
                            Diameter = "DN200",
                            DrawingPosition = "S-01",
                            IsDeleted = false,
                            Name = "Stehování",
                            OperationId = 2,
                            ProductSizeId = 3,
                            Sequence = 1,
                            StandardHour = 30
                        },
                        new
                        {
                            OperationStepId = 12,
                            Diameter = "DN200",
                            DrawingPosition = "S-02",
                            IsDeleted = false,
                            Name = "Svařování MIG",
                            OperationId = 2,
                            ProductSizeId = 3,
                            Sequence = 2,
                            StandardHour = 80
                        },
                        new
                        {
                            OperationStepId = 13,
                            Diameter = "DN100",
                            DrawingPosition = "T-01",
                            IsDeleted = false,
                            Name = "Kontrola materiálu",
                            OperationId = 3,
                            ProductSizeId = 2,
                            Sequence = 1,
                            StandardHour = 5
                        },
                        new
                        {
                            OperationStepId = 14,
                            Diameter = "DN100",
                            DrawingPosition = "T-02",
                            IsDeleted = false,
                            Name = "Řezání + zkosení",
                            OperationId = 3,
                            ProductSizeId = 2,
                            Sequence = 2,
                            StandardHour = 20
                        },
                        new
                        {
                            OperationStepId = 15,
                            Diameter = "DN300",
                            DrawingPosition = "T-01",
                            IsDeleted = false,
                            Name = "Kontrola materiálu",
                            OperationId = 3,
                            ProductSizeId = 4,
                            Sequence = 1,
                            StandardHour = 8
                        },
                        new
                        {
                            OperationStepId = 16,
                            Diameter = "DN300",
                            DrawingPosition = "T-02",
                            IsDeleted = false,
                            Name = "Plasma řezání + zkosení",
                            OperationId = 3,
                            ProductSizeId = 4,
                            Sequence = 2,
                            StandardHour = 35
                        },
                        new
                        {
                            OperationStepId = 17,
                            Diameter = "DN100",
                            DrawingPosition = "S-01",
                            IsDeleted = false,
                            Name = "Stehování",
                            OperationId = 4,
                            ProductSizeId = 2,
                            Sequence = 1,
                            StandardHour = 25
                        },
                        new
                        {
                            OperationStepId = 18,
                            Diameter = "DN100",
                            DrawingPosition = "S-02",
                            IsDeleted = false,
                            Name = "Kořenový svar TIG",
                            OperationId = 4,
                            ProductSizeId = 2,
                            Sequence = 2,
                            StandardHour = 40
                        },
                        new
                        {
                            OperationStepId = 19,
                            Diameter = "DN100",
                            DrawingPosition = "S-03",
                            IsDeleted = false,
                            Name = "Výplňové vrstvy MIG",
                            OperationId = 4,
                            ProductSizeId = 2,
                            Sequence = 3,
                            StandardHour = 60
                        },
                        new
                        {
                            OperationStepId = 20,
                            Diameter = "DN300",
                            DrawingPosition = "S-01",
                            IsDeleted = false,
                            Name = "Stehování",
                            OperationId = 4,
                            ProductSizeId = 4,
                            Sequence = 1,
                            StandardHour = 40
                        },
                        new
                        {
                            OperationStepId = 21,
                            Diameter = "DN300",
                            DrawingPosition = "S-02",
                            IsDeleted = false,
                            Name = "Kořenový svar TIG",
                            OperationId = 4,
                            ProductSizeId = 4,
                            Sequence = 2,
                            StandardHour = 70
                        },
                        new
                        {
                            OperationStepId = 22,
                            Diameter = "DN300",
                            DrawingPosition = "S-03",
                            IsDeleted = false,
                            Name = "Výplňové vrstvy MIG",
                            OperationId = 4,
                            ProductSizeId = 4,
                            Sequence = 3,
                            StandardHour = 110
                        },
                        new
                        {
                            OperationStepId = 23,
                            Diameter = "DN100",
                            DrawingPosition = "Z-01",
                            IsDeleted = false,
                            Name = "Instalace přístrojů",
                            OperationId = 5,
                            ProductSizeId = 2,
                            Sequence = 1,
                            StandardHour = 15
                        },
                        new
                        {
                            OperationStepId = 24,
                            Diameter = "DN100",
                            DrawingPosition = "Z-02",
                            IsDeleted = false,
                            Name = "Tlaková zkouška 1.5x PN",
                            OperationId = 5,
                            ProductSizeId = 2,
                            Sequence = 2,
                            StandardHour = 30
                        },
                        new
                        {
                            OperationStepId = 25,
                            Diameter = "DN300",
                            DrawingPosition = "Z-01",
                            IsDeleted = false,
                            Name = "Instalace přístrojů",
                            OperationId = 5,
                            ProductSizeId = 4,
                            Sequence = 1,
                            StandardHour = 20
                        },
                        new
                        {
                            OperationStepId = 26,
                            Diameter = "DN300",
                            DrawingPosition = "Z-02",
                            IsDeleted = false,
                            Name = "Tlaková zkouška 1.5x PN",
                            OperationId = 5,
                            ProductSizeId = 4,
                            Sequence = 2,
                            StandardHour = 45
                        },
                        new
                        {
                            OperationStepId = 27,
                            Diameter = "DN200",
                            DrawingPosition = "N-01",
                            IsDeleted = false,
                            Name = "Válcování plechu",
                            OperationId = 6,
                            ProductSizeId = 3,
                            Sequence = 1,
                            StandardHour = 60
                        },
                        new
                        {
                            OperationStepId = 28,
                            Diameter = "DN200",
                            DrawingPosition = "N-02",
                            IsDeleted = false,
                            Name = "Podélný svar pláště",
                            OperationId = 6,
                            ProductSizeId = 3,
                            Sequence = 2,
                            StandardHour = 90
                        },
                        new
                        {
                            OperationStepId = 29,
                            Diameter = "DN500",
                            DrawingPosition = "N-01",
                            IsDeleted = false,
                            Name = "Válcování plechu",
                            OperationId = 6,
                            ProductSizeId = 5,
                            Sequence = 1,
                            StandardHour = 120
                        },
                        new
                        {
                            OperationStepId = 30,
                            Diameter = "DN500",
                            DrawingPosition = "N-02",
                            IsDeleted = false,
                            Name = "Podélný svar pláště",
                            OperationId = 6,
                            ProductSizeId = 5,
                            Sequence = 2,
                            StandardHour = 180
                        },
                        new
                        {
                            OperationStepId = 31,
                            Diameter = "DN200",
                            DrawingPosition = "D-01",
                            IsDeleted = false,
                            Name = "Přivaření eliptického dna",
                            OperationId = 7,
                            ProductSizeId = 3,
                            Sequence = 1,
                            StandardHour = 80
                        },
                        new
                        {
                            OperationStepId = 32,
                            Diameter = "DN200",
                            DrawingPosition = "D-02",
                            IsDeleted = false,
                            Name = "Přivaření hrdel",
                            OperationId = 7,
                            ProductSizeId = 3,
                            Sequence = 2,
                            StandardHour = 50
                        },
                        new
                        {
                            OperationStepId = 33,
                            Diameter = "DN500",
                            DrawingPosition = "D-01",
                            IsDeleted = false,
                            Name = "Přivaření eliptického dna",
                            OperationId = 7,
                            ProductSizeId = 5,
                            Sequence = 1,
                            StandardHour = 150
                        },
                        new
                        {
                            OperationStepId = 34,
                            Diameter = "DN500",
                            DrawingPosition = "D-02",
                            IsDeleted = false,
                            Name = "Přivaření hrdel",
                            OperationId = 7,
                            ProductSizeId = 5,
                            Sequence = 2,
                            StandardHour = 100
                        },
                        new
                        {
                            OperationStepId = 35,
                            Diameter = "DN200",
                            DrawingPosition = "K-01",
                            IsDeleted = false,
                            Name = "RT / UT kontrola svarů",
                            OperationId = 8,
                            ProductSizeId = 3,
                            Sequence = 1,
                            StandardHour = 60
                        },
                        new
                        {
                            OperationStepId = 36,
                            Diameter = "DN200",
                            DrawingPosition = "K-02",
                            IsDeleted = false,
                            Name = "Tlaková zkouška nádoby",
                            OperationId = 8,
                            ProductSizeId = 3,
                            Sequence = 2,
                            StandardHour = 90
                        },
                        new
                        {
                            OperationStepId = 37,
                            Diameter = "DN500",
                            DrawingPosition = "K-01",
                            IsDeleted = false,
                            Name = "RT / UT kontrola svarů",
                            OperationId = 8,
                            ProductSizeId = 5,
                            Sequence = 1,
                            StandardHour = 120
                        },
                        new
                        {
                            OperationStepId = 38,
                            Diameter = "DN500",
                            DrawingPosition = "K-02",
                            IsDeleted = false,
                            Name = "Tlaková zkouška nádoby",
                            OperationId = 8,
                            ProductSizeId = 5,
                            Sequence = 2,
                            StandardHour = 180
                        },
                        new
                        {
                            OperationStepId = 39,
                            Diameter = "DN200",
                            DrawingPosition = "NR-01",
                            IsDeleted = false,
                            Name = "Přesné řezání nerez",
                            OperationId = 9,
                            ProductSizeId = 3,
                            Sequence = 1,
                            StandardHour = 45
                        },
                        new
                        {
                            OperationStepId = 40,
                            Diameter = "DN200",
                            DrawingPosition = "NR-02",
                            IsDeleted = false,
                            Name = "Moření a pasivace",
                            OperationId = 9,
                            ProductSizeId = 3,
                            Sequence = 2,
                            StandardHour = 30
                        },
                        new
                        {
                            OperationStepId = 41,
                            Diameter = "DN200",
                            DrawingPosition = "NR-03",
                            IsDeleted = false,
                            Name = "TIG kořenový svar",
                            OperationId = 10,
                            ProductSizeId = 3,
                            Sequence = 1,
                            StandardHour = 60
                        },
                        new
                        {
                            OperationStepId = 42,
                            Diameter = "DN200",
                            DrawingPosition = "NR-04",
                            IsDeleted = false,
                            Name = "TIG výplňové vrstvy",
                            OperationId = 10,
                            ProductSizeId = 3,
                            Sequence = 2,
                            StandardHour = 90
                        },
                        new
                        {
                            OperationStepId = 43,
                            Diameter = "DN200",
                            DrawingPosition = "NR-05",
                            IsDeleted = false,
                            Name = "Vizuální + rozměrová kontrola",
                            OperationId = 10,
                            ProductSizeId = 3,
                            Sequence = 3,
                            StandardHour = 20
                        },
                        new
                        {
                            OperationStepId = 44,
                            Diameter = "DN50",
                            DrawingPosition = "VS-01",
                            IsDeleted = false,
                            Name = "Řezání trubek na délku",
                            OperationId = 11,
                            ProductSizeId = 1,
                            Sequence = 1,
                            StandardHour = 30
                        },
                        new
                        {
                            OperationStepId = 45,
                            Diameter = "DN50",
                            DrawingPosition = "VS-02",
                            IsDeleted = false,
                            Name = "Rozvrtání trubkovnice",
                            OperationId = 11,
                            ProductSizeId = 1,
                            Sequence = 2,
                            StandardHour = 60
                        },
                        new
                        {
                            OperationStepId = 46,
                            Diameter = "DN50",
                            DrawingPosition = "VS-03",
                            IsDeleted = false,
                            Name = "Zaválcování trubek",
                            OperationId = 11,
                            ProductSizeId = 1,
                            Sequence = 3,
                            StandardHour = 90
                        },
                        new
                        {
                            OperationStepId = 47,
                            Diameter = "DN200",
                            DrawingPosition = "VT-01",
                            IsDeleted = false,
                            Name = "Zasunutí svazku do pláště",
                            OperationId = 12,
                            ProductSizeId = 3,
                            Sequence = 1,
                            StandardHour = 45
                        },
                        new
                        {
                            OperationStepId = 48,
                            Diameter = "DN200",
                            DrawingPosition = "VT-02",
                            IsDeleted = false,
                            Name = "Přivaření trubkovnice",
                            OperationId = 12,
                            ProductSizeId = 3,
                            Sequence = 2,
                            StandardHour = 120
                        },
                        new
                        {
                            OperationStepId = 49,
                            Diameter = "DN200",
                            DrawingPosition = "VT-03",
                            IsDeleted = false,
                            Name = "Montáž přírub a hrdel",
                            OperationId = 12,
                            ProductSizeId = 3,
                            Sequence = 3,
                            StandardHour = 60
                        },
                        new
                        {
                            OperationStepId = 50,
                            Diameter = "DN200",
                            DrawingPosition = "VT-04",
                            IsDeleted = false,
                            Name = "Těsnostní zkouška výměníku",
                            OperationId = 12,
                            ProductSizeId = 3,
                            Sequence = 4,
                            StandardHour = 90
                        });
                });

            modelBuilder.Entity("Normative.Models.Table.Preparation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Fitter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PreparationTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductSizeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Welder")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("PreparationTypeId");

                    b.HasIndex("ProductSizeId");

                    b.ToTable("Preparations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fitter = 0.25m,
                            IsDeleted = false,
                            PreparationTypeId = 1,
                            ProductSizeId = 1,
                            Welder = 0.00m
                        },
                        new
                        {
                            Id = 2,
                            Fitter = 0.50m,
                            IsDeleted = false,
                            PreparationTypeId = 1,
                            ProductSizeId = 2,
                            Welder = 0.00m
                        },
                        new
                        {
                            Id = 3,
                            Fitter = 1.00m,
                            IsDeleted = false,
                            PreparationTypeId = 1,
                            ProductSizeId = 3,
                            Welder = 0.00m
                        },
                        new
                        {
                            Id = 4,
                            Fitter = 1.50m,
                            IsDeleted = false,
                            PreparationTypeId = 1,
                            ProductSizeId = 4,
                            Welder = 0.00m
                        },
                        new
                        {
                            Id = 5,
                            Fitter = 2.50m,
                            IsDeleted = false,
                            PreparationTypeId = 1,
                            ProductSizeId = 5,
                            Welder = 0.00m
                        },
                        new
                        {
                            Id = 6,
                            Fitter = 0.25m,
                            IsDeleted = false,
                            PreparationTypeId = 2,
                            ProductSizeId = 1,
                            Welder = 0.25m
                        },
                        new
                        {
                            Id = 7,
                            Fitter = 0.50m,
                            IsDeleted = false,
                            PreparationTypeId = 2,
                            ProductSizeId = 2,
                            Welder = 0.50m
                        },
                        new
                        {
                            Id = 8,
                            Fitter = 0.75m,
                            IsDeleted = false,
                            PreparationTypeId = 2,
                            ProductSizeId = 3,
                            Welder = 0.75m
                        },
                        new
                        {
                            Id = 9,
                            Fitter = 1.00m,
                            IsDeleted = false,
                            PreparationTypeId = 2,
                            ProductSizeId = 4,
                            Welder = 1.00m
                        },
                        new
                        {
                            Id = 10,
                            Fitter = 1.50m,
                            IsDeleted = false,
                            PreparationTypeId = 2,
                            ProductSizeId = 5,
                            Welder = 1.50m
                        },
                        new
                        {
                            Id = 11,
                            Fitter = 0.50m,
                            IsDeleted = false,
                            PreparationTypeId = 3,
                            ProductSizeId = 1,
                            Welder = 0.00m
                        },
                        new
                        {
                            Id = 12,
                            Fitter = 0.75m,
                            IsDeleted = false,
                            PreparationTypeId = 3,
                            ProductSizeId = 2,
                            Welder = 0.00m
                        },
                        new
                        {
                            Id = 13,
                            Fitter = 1.25m,
                            IsDeleted = false,
                            PreparationTypeId = 3,
                            ProductSizeId = 3,
                            Welder = 0.00m
                        },
                        new
                        {
                            Id = 14,
                            Fitter = 2.00m,
                            IsDeleted = false,
                            PreparationTypeId = 3,
                            ProductSizeId = 4,
                            Welder = 0.00m
                        },
                        new
                        {
                            Id = 15,
                            Fitter = 3.00m,
                            IsDeleted = false,
                            PreparationTypeId = 3,
                            ProductSizeId = 5,
                            Welder = 0.00m
                        },
                        new
                        {
                            Id = 16,
                            Fitter = 0.50m,
                            IsDeleted = false,
                            PreparationTypeId = 4,
                            ProductSizeId = 1,
                            Welder = 0.50m
                        },
                        new
                        {
                            Id = 17,
                            Fitter = 0.75m,
                            IsDeleted = false,
                            PreparationTypeId = 4,
                            ProductSizeId = 2,
                            Welder = 0.75m
                        },
                        new
                        {
                            Id = 18,
                            Fitter = 1.25m,
                            IsDeleted = false,
                            PreparationTypeId = 4,
                            ProductSizeId = 3,
                            Welder = 1.25m
                        },
                        new
                        {
                            Id = 19,
                            Fitter = 2.00m,
                            IsDeleted = false,
                            PreparationTypeId = 4,
                            ProductSizeId = 4,
                            Welder = 2.00m
                        },
                        new
                        {
                            Id = 20,
                            Fitter = 3.50m,
                            IsDeleted = false,
                            PreparationTypeId = 4,
                            ProductSizeId = 5,
                            Welder = 3.50m
                        });
                });

            modelBuilder.Entity("Normative.Models.Table.ProductLine", b =>
                {
                    b.Property<int>("ProductLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductLine_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductLineId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.HasKey("ProductLineId")
                        .HasName("PK__VyrobekR__3214EC276286AE61");

                    b.ToTable("ProductLine");

                    b.HasData(
                        new
                        {
                            ProductLineId = 1,
                            IsDeleted = false,
                            Name = "Potrubí"
                        },
                        new
                        {
                            ProductLineId = 2,
                            IsDeleted = false,
                            Name = "Nádoby"
                        },
                        new
                        {
                            ProductLineId = 3,
                            IsDeleted = false,
                            Name = "Výměníky tepla"
                        });
                });

            modelBuilder.Entity("Normative.Models.Table.ProductSize", b =>
                {
                    b.Property<int>("ProductSizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductSize_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductSizeId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.Property<string>("Size")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ProductSizeId")
                        .HasName("PK__VyrobekV__3214EC27014D033A");

                    b.ToTable("ProductSize");

                    b.HasData(
                        new
                        {
                            ProductSizeId = 1,
                            IsDeleted = false,
                            Name = "DN 50",
                            Size = "DN50  / PN16"
                        },
                        new
                        {
                            ProductSizeId = 2,
                            IsDeleted = false,
                            Name = "DN 100",
                            Size = "DN100 / PN16"
                        },
                        new
                        {
                            ProductSizeId = 3,
                            IsDeleted = false,
                            Name = "DN 200",
                            Size = "DN200 / PN25"
                        },
                        new
                        {
                            ProductSizeId = 4,
                            IsDeleted = false,
                            Name = "DN 300",
                            Size = "DN300 / PN25"
                        },
                        new
                        {
                            ProductSizeId = 5,
                            IsDeleted = false,
                            Name = "DN 500",
                            Size = "DN500 / PN40"
                        });
                });

            modelBuilder.Entity("Normative.Models.Table.ProductType", b =>
                {
                    b.Property<int>("ProductTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductType_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductTypeId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.HasKey("ProductTypeId")
                        .HasName("PK__VyrobekT__3214EC27C0ED5D98");

                    b.ToTable("ProductType");

                    b.HasData(
                        new
                        {
                            ProductTypeId = 1,
                            IsDeleted = false,
                            Name = "Standardní"
                        },
                        new
                        {
                            ProductTypeId = 2,
                            IsDeleted = false,
                            Name = "Tlakový"
                        },
                        new
                        {
                            ProductTypeId = 3,
                            IsDeleted = false,
                            Name = "Nerezový"
                        });
                });

            modelBuilder.Entity("Normative.Models.V_Preparation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiameterLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fitter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Welder")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("V_Preparation");
                });

            modelBuilder.Entity("Normative.Models.V_VTC_InnerVessel_OPSQ_10", b =>
                {
                    b.Property<int?>("D1350")
                        .HasColumnType("int");

                    b.Property<int?>("D1700")
                        .HasColumnType("int");

                    b.Property<int?>("D2100")
                        .HasColumnType("int");

                    b.Property<int?>("D2500")
                        .HasColumnType("int");

                    b.Property<string>("NameOperationStep")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("OperationId")
                        .HasColumnType("int")
                        .HasColumnName("Operation_Id");

                    b.Property<string>("Option")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductLine")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.Property<int?>("ProductSizeId")
                        .HasColumnType("int")
                        .HasColumnName("ProductSize_Id");

                    b.Property<string>("ProductType")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("v_VTC_InnerVessel_OPSQ_10", (string)null);
                });

            modelBuilder.Entity("Normative.Models.V_VTC_InnerVessel_OPSQ_20", b =>
                {
                    b.Property<int?>("D1350")
                        .HasColumnType("int");

                    b.Property<int?>("D1700")
                        .HasColumnType("int");

                    b.Property<int?>("D2100")
                        .HasColumnType("int");

                    b.Property<int?>("D2500")
                        .HasColumnType("int");

                    b.Property<string>("DrawingPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOperationStep")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("OperationId")
                        .HasColumnType("int")
                        .HasColumnName("Operation_Id");

                    b.Property<string>("Option")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductLine")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.Property<int?>("ProductSizeId")
                        .HasColumnType("int")
                        .HasColumnName("ProductSize_Id");

                    b.Property<string>("ProductType")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("v_VTC_InnerVessel_OPSQ_20", (string)null);
                });

            modelBuilder.Entity("Normative.Models.V_VTC_InnerVessel_OPSQ_40", b =>
                {
                    b.Property<int?>("D1350")
                        .HasColumnType("int");

                    b.Property<int?>("D1700")
                        .HasColumnType("int");

                    b.Property<int?>("D2100")
                        .HasColumnType("int");

                    b.Property<int?>("D2500")
                        .HasColumnType("int");

                    b.Property<string>("DrawingPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOperationStep")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("OperationId")
                        .HasColumnType("int")
                        .HasColumnName("Operation_Id");

                    b.Property<string>("Option")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductLine")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.Property<int?>("ProductSizeId")
                        .HasColumnType("int")
                        .HasColumnName("ProductSize_Id");

                    b.Property<string>("ProductType")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("v_VTC_InnerVessel_OPSQ_40", (string)null);
                });

            modelBuilder.Entity("Normative.Models.V_VTC_OutherVessel_OPSQ_10", b =>
                {
                    b.Property<int?>("D1800")
                        .HasColumnType("int");

                    b.Property<int?>("D2100")
                        .HasColumnType("int");

                    b.Property<int?>("D2500")
                        .HasColumnType("int");

                    b.Property<int?>("D3000")
                        .HasColumnType("int");

                    b.Property<string>("NameOperationStep")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("OperationId")
                        .HasColumnType("int")
                        .HasColumnName("Operation_Id");

                    b.Property<string>("Option")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProductLine")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.Property<string>("ProductType")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("v_VTC_OutherVessel_OPSQ_10", (string)null);
                });

            modelBuilder.Entity("Normative.Models.V_VTC_OutherVessel_OPSQ_20", b =>
                {
                    b.Property<int?>("D1800")
                        .HasColumnType("int");

                    b.Property<int?>("D2100")
                        .HasColumnType("int");

                    b.Property<int?>("D2500")
                        .HasColumnType("int");

                    b.Property<int?>("D3000")
                        .HasColumnType("int");

                    b.Property<string>("DrawingPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOperationStep")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("OperationId")
                        .HasColumnType("int")
                        .HasColumnName("Operation_Id");

                    b.Property<string>("Option")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProductLine")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.Property<string>("ProductType")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("v_VTC_OutherVessel_OPSQ_20", (string)null);
                });

            modelBuilder.Entity("Normative.Models.V_VTC_OutherVessel_OPSQ_40", b =>
                {
                    b.Property<int?>("D1800")
                        .HasColumnType("int");

                    b.Property<int?>("D2100")
                        .HasColumnType("int");

                    b.Property<int?>("D2500")
                        .HasColumnType("int");

                    b.Property<int?>("D3000")
                        .HasColumnType("int");

                    b.Property<string>("DrawingPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOperationStep")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("OperationId")
                        .HasColumnType("int")
                        .HasColumnName("Operation_Id");

                    b.Property<string>("Option")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProductLine")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.Property<string>("ProductType")
                        .HasMaxLength(63)
                        .IsUnicode(false)
                        .HasColumnType("varchar(63)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("v_VTC_OutherVessel_OPSQ_40", (string)null);
                });

            modelBuilder.Entity("Normative.Models.View.ViewPermission", b =>
                {
                    b.Property<string>("PermitionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermitionValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("V_ViewPermission", (string)null);
                });

            modelBuilder.Entity("Normative.Models.Config.RolePermission", b =>
                {
                    b.HasOne("Normative.Models.Config.Permissions", "Permission")
                        .WithMany("Roles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Normative.Models.Config.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Normative.Models.Config.UserRole", b =>
                {
                    b.HasOne("Normative.Models.Config.Role", "Role")
                        .WithMany("UsersWithRole")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Normative.Models.Config.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Normative.Models.Table.Operation", b =>
                {
                    b.HasOne("Normative.Models.Table.ProductLine", "ProductLine")
                        .WithMany("Operation")
                        .HasForeignKey("ProductLineId")
                        .HasConstraintName("FK_Operation_ProductLine");

                    b.HasOne("Normative.Models.Table.ProductType", "ProductType")
                        .WithMany("Operation")
                        .HasForeignKey("ProductTypeId")
                        .HasConstraintName("FK_Operation_ProductType");

                    b.Navigation("ProductLine");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Normative.Models.Table.OperationStep", b =>
                {
                    b.HasOne("Normative.Models.Table.Operation", "Operation")
                        .WithMany("OperationStep")
                        .HasForeignKey("OperationId")
                        .HasConstraintName("FK_OperationStep_Operation");

                    b.HasOne("Normative.Models.Table.ProductSize", "ProductSize")
                        .WithMany("OperationStep")
                        .HasForeignKey("ProductSizeId")
                        .HasConstraintName("FK_OperationStep_ProductSize");

                    b.Navigation("Operation");

                    b.Navigation("ProductSize");
                });

            modelBuilder.Entity("Normative.Models.Table.Preparation", b =>
                {
                    b.HasOne("Normative.Models.PreparationType", "PreparationType")
                        .WithMany()
                        .HasForeignKey("PreparationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Normative.Models.Table.ProductSize", "ProductSize")
                        .WithMany()
                        .HasForeignKey("ProductSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreparationType");

                    b.Navigation("ProductSize");
                });

            modelBuilder.Entity("Normative.Models.Config.Permissions", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Normative.Models.Config.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UsersWithRole");
                });

            modelBuilder.Entity("Normative.Models.Config.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Normative.Models.Table.Operation", b =>
                {
                    b.Navigation("OperationStep");
                });

            modelBuilder.Entity("Normative.Models.Table.ProductLine", b =>
                {
                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Normative.Models.Table.ProductSize", b =>
                {
                    b.Navigation("OperationStep");
                });

            modelBuilder.Entity("Normative.Models.Table.ProductType", b =>
                {
                    b.Navigation("Operation");
                });
#pragma warning restore 612, 618
        }
    }
}
